[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]


[network.sepolia]
url = "https://eth-sepolia.g.alchemy.com/v2/upJrgNFSxUudWb1oHCQMtL4N5c6mSAUQ"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
